# Generated by Django 6.0 on 2025-12-04 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bulk_transfers', '0001_initial'),
        ('transfert', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulktransferjob',
            name='submitter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transfert.account'),
        ),
    ]
