# Generated by Django 6.0 on 2025-12-04 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulk_transfers', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulktransferjob',
            name='default_currency',
            field=models.CharField(default='USD', max_length=10),
        ),
        migrations.AddField(
            model_name='bulktransferjob',
            name='default_receiver_type',
            field=models.CharField(default='MSISDN', max_length=32),
        ),
    ]
