# Generated by Django 6.0 on 2025-12-04 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulk_transfers', '0003_bulktransferjob_default_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulktransferjob',
            name='default_currency',
        ),
        migrations.RemoveField(
            model_name='bulktransferjob',
            name='default_receiver_type',
        ),
    ]
