# Generated by Django 4.2.7 on 2025-12-04 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulk_transfers', '0004_remove_bulktransferjob_default_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulktransferjob',
            name='echoue_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bulktransferjob',
            name='reussi_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bulktransferjob',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
