# Generated by Django 4.2.7 on 2025-12-04 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulk_transfers', '0005_bulktransferjob_echoue_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulktransferjob',
            name='message_execution',
            field=models.TextField(blank=True, default='Traitement en cours...', null=True),
        ),
    ]
