# Generated by Django 6.0 on 2025-12-04 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfert', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='home_transaction_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
