# Generated by Django 6.0 on 2025-12-04 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfert', '0002_alter_transfer_home_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='transfer_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
