# Generated by Django 6.0 on 2025-12-04 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfert', '0003_alter_transfer_transfer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='currency',
            field=models.CharField(default='USD', max_length=10),
        ),
    ]
