# Generated by Django 6.0 on 2025-12-04 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfert', '0004_transfer_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
