# Generated by Django 6.0 on 2025-12-04 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfert', '0005_alter_transfer_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='note',
            field=models.CharField(blank=True, default='Transfert P2P', max_length=255),
        ),
    ]
