# Generated by Django 4.2.7 on 2025-12-04 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfert', '0007_alter_account_id_alter_transfer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='nom_complet',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='valeur_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
